name: Release Automation

on:
  repository_dispatch:
    types: [ tag-pushed ]



jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 执行Release流程
        env:
          ACCESS_GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          node src/index.js release \
            "${{ github.event.client_payload.tag_name }}" \
            "${{ github.event.client_payload.previous_tag_commit }}" \
            "${{ github.event.client_payload.current_tag_commit }}" \
            "${{ github.sha }}"
